### ISSUE TITLE
[ui5-middleware-cfdestination] UAA issues

### ISSUE THREAD

**Issue by piejanssens** [ui5-community/ui5-ecosystem-showcase#817] opened 2023-08-30 11:04 UTC
- in case UAA session has timed out, UI5 tooling (8080) will just report 401 errors, while the real approuter process (5000/5000) would kickoff re-auth process

Related @sap/approuter docu: https://www.npmjs.com/package/@sap/approuter#session-handling

- in case a new UAA session is required (upon re-running ui5 serve, the @sap/approuter will send a redirect to the callback on the approuter port after which you manually have to change the URL back to '8080'

As noted by @petermuessig in https://github.com/ui5-community/ui5-ecosystem-showcase/issues/814#issuecomment-1698107415, this could be resolved after switching to `http-proxy-middleware`

- UI5 serve is not proxying /login/callback to @sap/approuter

**Comment by petermuessig** [comment] 2023-08-31 06:19
Should be fixed with `ui5-middleware-cfdestination` version `3.1.0` which will be released just right now! Please validate and let me know... THX!

**Comment by piejanssens** [comment] 2023-08-31 07:29
Hi @petermuessig,

The auth flow is not kicked off any longer. 

> If there is no session in the application router, either because there has been a session timeout or because no session has been created yet, and if the incoming request matches a non-public route, the application router triggers a redirect to the authentication service (UAA or IAS). After a successful login, a redirect back to application router takes place using the login callback endpoint, which triggers the creation of a new session. If the incoming request is an AJAX request (has the request header X-Requested-With: XMLHttpRequest) or if the HTTP verb is not GET and no session exists (there is no session cookie and the request doesn’t have an x-approuter-authorization header), the application router returns the response code 401 - Unauthorized. This enables the client application to handle the 401 response before it navigates to the authentication service. For example, the application can store data entered by the user and prevent data loss. When the handling of the 401 response is completed, the client application should send a request without an xmlhttprequest object to trigger the application router authentication flow.

OData requests performed by UI5 include the header X-Requested-With: XMLHttpRequest. I'm seeing 401 being returned by the approuter, which is correct according to the documentation. The problem I think is that there is no route being accessed on the approuter that does not contain this header (e.g. no request to HTML5 repo service or a static resource protected by XSUAA), which would have gotten a valid session before UI5 is accessing XSUAA procted resources.

This means for `ui5 serve` it's '/' that should be a route handled by @sap/approuter and considerd a non-public route.
As a hack around this I tried adding this route in the xs-app.json:

```
    {
      "source": "^/",
      "localDir": "webapp",
      "target": "/",
      "authenticationType": "xsuaa"
    },
```

This then does kick off the auth flow, but then it stops at the callback to `http://localhost:5005/login/callback?code=jBiR63olHXzptFJQwCYcC4ON7hYKV7kQ`. Network trace shows a "400 Signature does not match" which I assume is coming from @sap/approuter. Changing the port manually to 8080 at that point returns the same status.

Looking at the trace I see that the callback URL+PORT is determined by the requestor (@sap/approuter) and it's included as a URI parameter in the request to UAA:
`/oauth/authorize?response_type=code&client_id=sb-na-bea977db-68ab-48d1-9026-c07fd6d0d1bf!t1367&redirect_uri=http%3A%2F%2Flocalhost%3A5005%2Flogin%2Fcallback``

 Before we look into solving forcing xsuaa flow on '/' (when authenticationMethod is set to 'routet') and rewriting the port in the `redirect_uri`parameter, we should find a way to resolve the "signature does not match" error.

**Comment by piejanssens** [comment] 2023-08-31 10:35
After debugging the `@sap/approuter` signature verification flow, I noticed a difference between the signature being set by the HTTP response ("/index.html") and the signature verification flow ("/"). I got rid of `ui5-middleware-index` to cope with this.

After loading the xs-app config, we should delete the "welcomeFile" property (we don't want to redirect the home page when loading `ui5 serve`: https://github.com/ui5-community/ui5-ecosystem-showcase/pull/820

New issue with `http-proxy-middleware`: **every other** (literally alternating) request to CAP backend returns the metadata response or an error message `Error fetching proxied request: unexpected end of file`.  For the record, same URL but requesting directly to approuter on 5005 does not give any issue.

Remaining issue: we need a way to kick off the auth flow (if authenticationMethod is set to 'route') on requesting '/'.

**Comment by piejanssens** [comment] 2023-09-01 15:12
@petermuessig See https://github.com/piejanssens/sample-ui5-uaa 
This works on a trial account too.

**Comment by petermuessig** [comment] 2023-09-02 16:56
Thanks for your example - I could reproduce the issue. But I think we need to find a better way for the authentication. An authentication using the OData metadata request isn't a good idea. The XHR doesn't understand the SAML auth flow and would try to parse the HTML response for the SAML auth. Normally, the HTML page should do the authentication. I was wondering about the timeout handling - whether a SAML re-auth has been implemented for the OData services. For that I might need to ask my colleagues after my vacation...

**Comment by petermuessig** [comment] 2023-09-02 17:03
When using the following start command the login happens as expected: 

```sh
npm run serve -- -o webapp/index.html
```

It's as you wrote, important to use the correct welcome page! Need to understand the flow in more depth...

**Comment by petermuessig** [comment] 2023-09-02 22:32
Finally, got it! 

The `http-proxy-middleware` supports `X-Forward-*` headers which tells the approuter to redirect to another page. Besides that I introduced some proper redirections, so that the `ui5-middleware-index` and the `ui5-middleware-cfdestination` now play properly together with the welcome file. I added also proper support to trigger the login for all html pages of the UI5 server app. This should now do this trick and I will also upload a PR for your example... 

Release follows later...

**Comment by petermuessig** [comment] 2023-09-03 06:35
I keep the ticket open to report back the validation results - release about to come...

**Comment by petermuessig** [comment] 2023-09-03 08:22
Released the following versions: 

```sh
Changes:
 - ui5-middleware-cfdestination: 3.1.1 => 3.1.2
 - ui5-middleware-index: 3.0.0 => 3.0.1
```

**Comment by piejanssens** [comment] 2023-09-04 09:11
@petermuessig Impressive stuff! It's working great now.

To take it one step further now 😄 I tried it with `cds-plugin-ui5`, but that doesn't seem to proxy `/login/callback`.
Looking at the logs upon runnning `cds watch`, I don't see `ui5-middleware-index`or `ui5-middleware-cfdestination` loading up...

**Comment by piejanssens** [comment] 2023-09-04 09:18
I've updated the sample.

**Comment by petermuessig** [comment] 2023-09-05 08:15
Ok, regarding the `cds-plugin-ui5`: the problem is that the `cfdestination` isn't aware about the router. I need to find out whether this can be detected generically and then I can rewrite the routes accordingly.

Regarding the `content-type` -  I need to check this again - this has been added by others before - I will also take a look into your PR...

**Comment by petermuessig** [comment] 2023-09-05 21:22
@piejanssens - the issue with the `content-type` has been fixed with the latest release of the `ui5-middleware-cfdestination`! The standard `/login/callback` can be used by making the single UI5 app in the CDS servers'  `app` folder mounted to the default path as suggested with the following PR:  https://github.com/piejanssens/sample-ui5-uaa/pull/2

Keeping the context path with the metadata name `sample.ui5.uaa.ui`, seems to be a bit more tricky. We have to handle the `302` response and redirect properly...

**Comment by petermuessig** [comment] 2023-09-06 06:47
I think now we need to discuss the rest in a bit more detail - the usage of the `mountPath: /` also has problems as the `/ci` route can't be accessed anymore since it is in conflict with the real `/ci` route of the CDS server. And when using the login mechanism from the context based url `/saple.ui5.uaa.ui` then I'm running in a login cycle of death. I think this requires a deeper understanding of the complete flow... 

The PR https://github.com/piejanssens/sample-ui5-uaa/pull/2 works for the application, but the data isn't loaded anymore - I didn't carefully check this...

**Comment by piejanssens** [comment] 2023-09-06 07:59
@petermuessig Thanks Peter. I'm going to perform some tests from my end to understand the issue with `cds-plugin-ui5` a bit better. If it's only a matter of conflict in the paths, then a notice in the README not to use the same paths for the CAP service in the approuter would be sufficient 😉 

I'm very glad to have `ui5-middleware-cfdestination" working with UAA!!

**Comment by petermuessig** [comment] 2023-09-06 21:02
Moving the application into the root path conflicts causes route conflicts between the CAP server and the `ui5-middleware-cfdestination` but the `login/callback` handling works then. 

Keeping the app in the app path gets rid of the path conflicts but therefore the `login/callback` flow is running into an circle of death! The problem here seems to be the cookie the UAA sets - this is a request from another domain / not proxied and it contains the root path for the cookie (unfortunately, I'm not the expert here) - I need to investigate this in more depth to get a proper understanding of the auth flow. For this flow, I patched the `ui5-middleware-cfdestination` to add the app path before the `login/callback` and does a proper rewriting of the paths again... No luck yet...

**Comment by petermuessig** [comment] 2023-09-07 08:47
@piejanssens after merging my recent changes and updating the PR https://github.com/piejanssens/sample-ui5-uaa/pull/2 on your repository, the UAA flow now also works for the nested path and the datasource request works properly now! Please test and give feedback... 😉

**Comment by petermuessig** [comment] 2023-09-21 14:28
Closing the issue as @piejanssens confirmed that it is fixed now! THX for reporting! 😄

**Closed by petermuessig** 2023-09-21 14:28 UTC
