### ISSUE TITLE
App can't find external package after deployment

### ISSUE THREAD

**Issue by MillCreeker** [ui5-community/ui5-ecosystem-showcase#849] opened 2023-09-27 07:31 UTC
I followed the instructions, and they work perfectly fine when running the app locally.
When deploying the app, tho, it says "failed to load 'tesseract.js.js' from /sap/bc/ui5_ui5/ui2/ushell/resources[...]".

 - Browser: Chrome
 - Chrome version: 115.0.5790.171
 - Fiori version: 1.71.47
 - UI5 version: 3.6.0
 - ui5-tooling-modules version: 3.0.8

## ui5.yaml
```yaml
specVersion: "3.0"
metadata:
  name: <com.my.org>
type: application
builder:
  customTasks:
    - name: ui5-tooling-modules-task
      afterTask: replaceVersion
server:
  customMiddleware:
    - name: ui5-tooling-modules-middleware
      afterMiddleware: compression
    - name: fiori-tools-proxy
      afterMiddleware: ui5-tooling-modules-middleware
      configuration:
        ignoreCertError: true
        ui5:
          path:
            - /resources
            - /test-resources
          url: https://ui5.sap.com
        backend:
          - path: /sap
            url: <url>
            client: '001'
    - name: fiori-tools-appreload
      afterMiddleware: compression
      configuration:
        port: <port>
        path: webapp
        delay: 300
    - name: fiori-tools-preview
      afterMiddleware: fiori-tools-appreload
      configuration:
        component: <com.my.org>
        ui5Theme: sap_fiori_3
```

## package.json
```json
{
    "name": "myApp",
    "version": "0.0.1",
    "private": true,
    "description": "A Fiori application.",
    "keywords": [
        "ui5",
        "openui5",
        "sapui5"
    ],
    "main": "webapp/index.html",
    "dependencies": {
        "cordova": "^6.1.1",
        "latest": "^0.2.0",
        "node": "^16.0.0",
        "node.js": "^0.0.1-security",
        "tesseract.js": "^4.1.2"
    },
    "devDependencies": {
        "@sap/ux-ui5-tooling": "^1.9.5",
        "@ui5/cli": "^3.6.0",
        "rimraf": "^3.0.2",
        "ui5-task-flatten-library": "0.2.5",
        "ui5-tooling-modules": "*"
    },
    "scripts": {
        [...]
    },
    "sapuxLayer": "CUSTOMER_BASE",
    "ui5": {
        "dependencies": [
            "ui5-task-flatten-library"
        ]
    }
}
```

## ui5-deploy.yaml
```yaml
# yaml-language-server: $schema=https://sap.github.io/ui5-tooling/schema/ui5.yaml.json

specVersion: "2.6"
metadata:
  name: <com.my.org>
type: application
resources:
  configuration:
    propertiesFileSourceEncoding: UTF-8
builder:
  resources:
    excludes:
      - /test/**
      - /localService/**
      - /node_modules/
  customTasks:
    - name: deploy-to-abap
      afterTask: generateCachebusterInfo
      configuration:
        ignoreCertError: true
        target:
          url: <url>
          client: "<client>"
          auth: basic
          credentials:
          username: env.DEPLOYMENT_USER
          password: env.DEPLOYMENT_PASSWORD
        app:
          name: <MY_APP>
          description: <My_app>
          package: <Z_PACKAGE>
          transport: <transport>
        exclude:
          - /test/
```

I hope it's not because the *ui5-deploy.yaml*'s *specVersion* is below *3.0*. When changing it, the deployment doesn't work. In this case, we'd have to change our live UI5 version (I think).

**Comment by petermuessig** [comment] 2023-09-30 07:15
@MillCreeker 

did you try the `addToNamespace` option for the task?

```yaml
builder:
  customTasks:
    - name: ui5-tooling-modules-task
      afterTask: replaceVersion
      configuration:
        addToNamespace: true
```

This option copies the external package into the namespace of the application under `thirdparty` and rewrites all usages via `sap.ui.define`, `sap.ui.require`, and `sap.ui.require.toUrl` so that this external package becomes an exclusive one for your application inside the local namespace.

HTH

**Comment by MillCreeker** [comment] 2023-10-02 05:31
@petermuessig

Thx for your answer. Unfortunately tho, it didn't work:
![image](https://github.com/ui5-community/ui5-ecosystem-showcase/assets/59824109/fe6cdef7-7302-4eb3-89d1-733f89a1a75f)

**Comment by petermuessig** [comment] 2023-10-02 06:03
This means the `dist` folder contains now files which cannot be uploaded to the BSP respository. As the thirdparty files are now included into the `dist/thirdparty` folder and I remember some restrictions for file and folder names and length - maybe this is the issue now it hits. 

AFAICS, you are consuming a lot of dependencies - where I'm even not sure which of them is really necessary for the client-side: 

```json
{
    [...]
    "dependencies": {
        "cordova": "^6.1.1",
        "latest": "^0.2.0",
        "node": "^16.0.0",
        "node.js": "^0.0.1-security",
        "tesseract.js": "^4.1.2"
    },
    [...]
}

From error message perspective, I would assume you need the `tesseract.js` and `cordova` - the latter dependency is a big one which may include several files. What I could see as a problem is for sure the amount of files `cordova` needs and is most probably included - and those files are using `_` and `.` charaters in their file name. Additionally, `tesseract.js` has a dot in its package name which creates the folder `tesseract.js` in the `dist/thirdparty` folder. This folder name having a dot could be the issue. Unfortuntately, right now, the `ui5-tooling-modules` doesn't support an aliasing of package names which may help here if the dot is the root cause for the deployment, but I need to know whether this is really the case.

BTW: is there any possibility to get more details from the upload issue? It also mentions, that the app can't be deleted because of nested folders in `dist/` - maybe you can delete it manually and then upload again?

Cc: @tobiasqueck @silkearians @MatthiasSchmalz -> is there any documentation about the restrictions of the BSP repository? any help to get a more verbose error message from the abap backend?

**Comment by MillCreeker** [comment] 2023-10-02 06:10
In my case, I bypassed the problem by finding a minified version of tesseract.js and accessing it via its own JS file.
Still grateful for the help, though ^^

**Comment by petermuessig** [comment] 2023-10-02 06:24
You only need tesseract.js for the deployment? Did you check whether the `.` in the folder name `dist/thirdparty/tesseract.js` is the issue? You can rename it and check whether the deployment works. If this is the case, I could provide you an aliasing for package names so that you can control the folder name...

**Comment by MatthiasSchmalz** [comment] 2023-10-02 07:10
@petermuessig there is no problem deploying files or folders which contain . - or \_  
Problematic chars are { and } because they have no valid runtime URL.  
@MillCreeker the error message in the log seems to be a known issue which should be solved with note https://launchpad.support.sap.com/#/notes/3089702

**Comment by petermuessig** [comment] 2023-10-05 06:53
@MillCreeker is your issue fixed now?

**Comment by petermuessig** [comment] 2023-10-18 22:09
No response => closing the issue

**Closed by petermuessig** 2023-10-18 22:09 UTC
Labels: author action
