### ISSUE TITLE
[ui5-task-zipper] shimmed dependency missing in bundle after update to 0.7.4

### ISSUE THREAD

**Issue by LukasHeimann** [ui5-community/ui5-ecosystem-showcase#699] opened 2023-03-27 07:09 UTC
**Describe the bug**

In our application, we include a third-party dependency in the "old-fashioned" way via a shim:

```yml
builder:
  settings:
    includeDependency:
      - "unleash-proxy-client"
  customTasks:
    - name: ui5-task-zipper
      afterTask: generateVersionInfo
      configuration:
        archiveName: my.app
        includeDependencies: true

---
specVersion: "3.0"
kind: extension
type: project-shim
metadata:
  name: my.app.thirdparty
shims:
  configurations:
    unleash-proxy-client: # dependency name as defined in package.json
      specVersion: "3.0"
      type: module
      metadata:
        name: unleash-proxy-client
      resources:
        configuration:
          paths:
            "/lib/unleash-proxy-client/": "build"
```

After the update to UI5 0.7.4, however, the dependency is not in the ZIP anymore. The log output looks okay, though:

```
info ProjectBuilder Preparing build for project my.app
info ProjectBuilder   Target directory: ./dist
info ProjectBuilder   Including all dependencies
info ProjectBuilder Processing 2 projects
info ProjectBuilder Cleaning target directory...
info Project 1 of 2: ❯ Building module project unleash-proxy-client...
info Project 2 of 2: ❯ Building application project my.app...
info my.app › Running task escapeNonAsciiCharacters...
info my.app › Running task replaceCopyright...
info my.app › Running task replaceVersion...
info my.app › Running task minify...
info my.app › Running task generateFlexChangesBundle...
info my.app › Running task generateComponentPreload...
info my.app › Running task ui5-task-zipper...
```

I guess this is due to https://github.com/ui5-community/ui5-ecosystem-showcase/pull/692, and the test doesn't test with shimmed dependencies: https://github.com/ui5-community/ui5-ecosystem-showcase/blob/main/packages/ui5-task-zipper/test/zipper.test.js#L131

However, I am not sure if UI5 tooling's `availableDependencies` should include the the shimmed dependency or not... Or if the problem even comes afterwards, when the tooling doesn't pass the shim even if declared as dependency...

**To Reproduce**
I'll produce a minimum working (or rather failing) example and will provide it later

**Expected behavior**
The dependency is bundled in the zip.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Node: 18
 - UI5 CLI 3.0.5

**Comment by LukasHeimann** [comment] 2023-03-27 07:23
See https://github.com/LukasHeimann/shim-issue for a minimum example. With 0.7.4, the library is not included in the zip. Downgrading to 0.7.3, it is.

I have no idea, where the issue might come from :/

**Comment by petermuessig** [comment] 2023-03-28 18:20
Hi @LukasHeimann, the issue is related to the `determineRequiredDependencies` - the change @flovogt made assumes that the task is already based on `specVersion: 3.0`. Only then the configuration options are passed to the `determineRequiredDependencies` function. This is now a bit unfortunate and requires to read the `ui5.yaml` manually and extract the configuration from there. Or I need to find a different way. I'm also enhancing the tests to support this scenario...

**Comment by LukasHeimann** [comment] 2023-03-29 06:23
Ah, you mean at https://github.com/ui5-community/ui5-ecosystem-showcase/blob/main/packages/ui5-task-zipper/ui5.yaml#L2? That makes sense. And you don't want to raise this version to stay compatible with older versions of the cli, I guess...

**Comment by petermuessig** [comment] 2023-03-29 12:33
We plan to rework the UI5 tooling extensions of the ecosystem also at some point in time for v3. Till then, I want to ensure that the extensions work with V2 and V3 and the suggestion to @matz3 and @flovogt would be a fix in the UI5 Tooling V3 to also provide the configuration to the `determineRequiredDependencies` function which is IMO anyhow necessary. Didn't get feedback, yet.

**Comment by flovogt** [comment] 2023-03-29 14:26
Thanks a lot @LukasHeimann and @petermuessig for pointing this out.
We'll create a fix for this.

**Closed** 2023-03-30 14:58 UTC
