### ISSUE TITLE
ui5-middleware-cfdestination not working properly?

### ISSUE THREAD

**Issue by Smux** [ui5-community/ui5-ecosystem-showcase#515] opened 2021-04-20 11:50 UTC
Scenario:
I have a Fiori application (that should run on Cloud Foundry with managed app router) that uses the UI5 tooling. I added the cfdestination middleware like described in the npmjs readme and I can successfully add a URL for my "backend" destination.
![image](https://user-images.githubusercontent.com/19520637/115390363-71439c00-a1de-11eb-94ac-97c256449234.png)

However, this only works with a non-authenticated URL. I tried to add an SAP internal OnPremise URL that requires authentication. So I also tried adding the auhtneticationMethod: "route" and "xsuaa" to "authenticationType" of my destination. Also provided a .env and a default-env.json file with the bindings to the correct xsuaa, connectivity service and destination service where I also have added the destination to the on premise system. None of which worked. I always receive a 502 error for the request pointing out that there is no valid certificate.

So my quesiton would be:
How do I acually configure the cfdestination middleware (or maybe another middleware?) to connect my local project to: 
a) on premise systems 
b) other backends deployed on CF that need a valid JWT

And in general, when I want my applications env files to be filled, do I need to provide .env or default-env.json? Is this different in "normal" ui5 tooling set up and cfdestination middleware setup?

**Comment by vobu** [comment] 2021-04-23 07:04
on first look, this sounds more of an SSL certificate issue btw your computer and BTP's xsuaa.
i've seen successful configurations just like yours - have a destination that's protected by xsuaa; upon hitting the respecitve url, browser redirects to login screen, auth, ...
do you have a `default-env.json` in `/` with the required props for the xsuaa?

**Comment by Smux** [comment] 2021-04-23 11:37
I now tested it with a new and clean setup. The URL of my xsuaa protected node app is resolved properly, however I am receiving the error "Unauthorized" which is the response if no valid JWT was provided in the request. 

As I have an mta application and start the UI5 app from the root of the mta project, I was not sure where to put the default.env.json so I tried all possible locations and even copying the json in all possible directories, nothing worked. 
So I have no clue what to do differently as I did everything as described in the readme.. :(

**Comment by Smux** [comment] 2021-04-23 11:38
Btw. yes in the default-env.json I have provided the VCAP SERVICES of another approuter that has bound the same xsuaa instance so it should all be fine.

**Comment by Smux** [comment] 2021-04-23 11:45
![image](https://user-images.githubusercontent.com/19520637/115866539-14dcb880-a43a-11eb-9dba-136d4739abeb.png)
![image](https://user-images.githubusercontent.com/19520637/115866567-21611100-a43a-11eb-8b88-e537779a8d96.png)
![Uploading image.png…]()

**Comment by Smux** [comment] 2021-04-23 11:54
And my github repo:
https://github.com/Smux/ui5-cf-mw-test

**Comment by vobu** [comment] 2021-04-28 08:41
hi, thanks for providing that detailed feedback and code sample. and sorry for replying so late! just wanted to let you know that this is still on my radar, but time is scarce these days...i'll get back to you, promised, but can't put a time line on it.

**Comment by Smux** [comment] 2021-05-03 09:57
hello vobu,
no worries, i understand that. thanks for taking a look into this issue.

**Comment by vobu** [comment] 2021-05-12 07:06
just to let you know: on my list for friday

**Comment by Smux** [comment] 2021-05-20 14:12
@vobu Any updates yet? :) would be so great to know whether we can use this middleware to authenticate against a JWT secured deployed backend while developing locally :)

**Comment by vobu** [comment] 2021-05-26 13:40
with introducing tests to the `ui5-middleware-cfdestination`, I think I got the gist of things.  
Upfront: `@sap/approuter` only seems to play nice when _both_ `xs-app.json` and `default-env.json` reside at `/`, also outside `uimodule`:
```bash
$> tree -L 1 
.
├── approuter
├── default-env.json # <--
├── deployer
├── karma-ci.conf.js
├── karma.conf.js
├── mta.yaml
├── node_modules
├── package-lock.json
├── package.json
├── readme.md
├── uimodule
└── xs-app.json # <--
```

this should guarantee that both config files are picked up at run-/dev-time.

Plus, you should also try forwarding the auth token (=== `JWT`) on the configured on-prem route:
```json
"routes": [
    {
      "source": "^/on-prem/(.*)",
      "target": "$1",
      "forwardAuthToken": true,
      "destination": "onPrem"
    }
```

hth, v.

**Comment by Smux** [comment] 2021-05-26 13:45
Thanks for the update! So once it is merged I will try it again and give you an update as well whether it works for me :)

**Comment by Smux** [comment] 2021-06-09 14:24
Hello @vobu 
I noticed that you released the changes that should essentially fix this issue, however I tested it with the new version and it does not work :(

I tried by generating a new project with the easy-ui5 generator. I get the following structure:
![image](https://user-images.githubusercontent.com/19520637/121372179-5f5cba80-c93e-11eb-9420-526b3c3365b6.png)

I updated my ui5-middleware-cfdestination to 0.6.0
![image](https://user-images.githubusercontent.com/19520637/121372312-7a2f2f00-c93e-11eb-91eb-66c4352101c8.png)
It is also added in the ui5 dependencies within package.json

My uimodule has the following xs-app.json
![image](https://user-images.githubusercontent.com/19520637/121372438-9501a380-c93e-11eb-8451-12666af95a0d.png)

Middleware config within ui5.yaml on root of uimodule
![image](https://user-images.githubusercontent.com/19520637/121372508-a34fbf80-c93e-11eb-80ce-3beb7945d00f.png)

I filled my default-env.json file by using the default-env plugin to fetch the environment variables from my CAP backend on my trial account that I want to access. The XSUAA is bound within the CAP project and therefore also now in my default-env.json

However when I start the ui5 server it simply does not authenticate. I can route to the unprotected routes of my CAP backend. But as soon as I hit a route that requires authentication I receive 401 athough the everything is set up like described in your FAQ on npm.

I also tried to copy the default-env.json to any other possible folder of my project without success. It still does not work no matter what.

Was this ever tested on an XSUAA protected backend? When I fetch the token manually with the clientid and secret from the XSUAA credentials in my default-env.json I am able to authenticate, but with the middleware it is not working.. :((

**Comment by stefania-santimbrean** [comment] 2021-06-13 16:33
@Smux in the ui5.yaml you need to define the destinations with **forwardAuthToken** like this:

```
configuration:
        destinations:
          - name: backend
            url: http://localhost:4004
            forwardAuthToken: true
```

Hope this helps :)

**Comment by Smux** [comment] 2021-06-14 13:08
@stefania-santimbrean still not working :(
401 unauthorized. default-env.json provided and everything set up as described
![image](https://user-images.githubusercontent.com/19520637/121897166-5e52d100-cd22-11eb-868b-9f20bcff118e.png)

It seems that when I make a request from the UI the authorization flow is not triggered by the middleware.

**Comment by vobu** [comment] 2021-06-14 13:29
another root cause could be similar to #508: the location of the `xs-app.json`. You have it at `/uimodule/webapp/`.  Please try placing it directly into `/` and see if that changes things

**Comment by Smux** [comment] 2021-06-14 14:06
Still not working :( 
Did you ever get it up and running with an xsuaa protected backend while developing it? Or is it unclear whether it is technically working at all?

**Comment by vobu** [comment] 2021-06-14 14:09
@rsletta, any field experiences you'd like to share? 😸

**Comment by ubheamar** [comment] 2021-06-25 18:16
I am also facing the same issue. I have put xs-app.json in the root directory. I am getting a 401 response code.
![image](https://user-images.githubusercontent.com/10156281/123468219-1d569880-d60f-11eb-97fe-0ea31ddb7e02.png)
I am able to access the first page of cloud but not able to access services.
![image](https://user-images.githubusercontent.com/10156281/123468430-61499d80-d60f-11eb-9df2-050dc06b7bea.png)
trying to execute metadata
![image](https://user-images.githubusercontent.com/10156281/123468492-76bec780-d60f-11eb-8208-1860c9b1628c.png)

**Comment by ubheamar** [comment] 2021-06-26 10:00
Thanks, the issue is resolved. I was getting an issue because I was missing last part of the URL in destination ui5.yml
xs-app.json
`{
  "welcomeFile": "uimodule/index.html",
  "authenticationMethod": "route",
  "logout": {
    "logoutEndpoint": "/do/logout"
  },
  "routes": [
    {
      "source": "^/uimodule/(.*)$",
      "target": "$1",
      "authenticationType": "none",
      "localDir": "uimodule/webapp"
    },
    {
      "source": "^/api/(.*)$",
      "target": "$1",
      "authenticationType": "xsuaa",
      "destination": "backend"
    }
  ]
}
`
ui5.yml
`server:
  customMiddleware:
    - name: ui5-middleware-livereload
      afterMiddleware: compression
      configuration:
        port: 35729
        path: uimodule/webapp
    - name: ui5-middleware-cfdestination
      afterMiddleware: compression
      configuration:
        debug: true
        port: 1091
        xsappJson: approuter/xs-app.json
        destinations: 
          - name : backend
            url: https://abc.us21.hana.ondemand.com.com/api/`

So in destinations i was passing URL: `https://abc.us21.hana.ondemand.com.com/` then I changed to  `https://abc.us21.hana.ondemand.com.com/api/` it was working fine

**Comment by vobu** [comment] 2021-06-28 06:19
probably a hint in there to also help you @Smux ?

**Comment by vobu** [comment] 2021-08-06 07:50
i'll close this for now - it's validated that the `cf-destination` middleware is working for a local runtime authenticating against a remote BTP instance.
to help resolve issues such as @Smux's, i was thinking about hosting a mob coding session some time anyway - sort of a "UI5ers live", only like "UI5ers coding live"...where anyone can participate and we hack together for an hour on multiple use cases - pingning @margopolo for that 🤙

**Closed by vobu** 2021-08-06 07:50 UTC

**Comment by luizcarlospedrosogomes** [comment] 2021-12-10 13:07
> @stefania-santimbrean still not working :( 401 unauthorized. default-env.json provided and everything set up as described ![image](https://user-images.githubusercontent.com/19520637/121897166-5e52d100-cd22-11eb-868b-9f20bcff118e.png)
> 
> It seems that when I make a request from the UI the authorization flow is not triggered by the middleware.

why port 1091?

**Comment by vobu** [comment] 2021-12-10 13:24
> > @stefania-santimbrean still not working :( 401 unauthorized. default-env.json provided and everything set up as described ![image](https://user-images.githubusercontent.com/19520637/121897166-5e52d100-cd22-11eb-868b-9f20bcff118e.png)
> > It seems that when I make a request from the UI the authorization flow is not triggered by the middleware.
> 
> why port 1091?

why not?

**Comment by luizcarlospedrosogomes** [comment] 2021-12-10 13:36
> why not?

![image](https://user-images.githubusercontent.com/9791364/145582003-161236d5-24ae-42dd-9cad-6db0e2fdab80.png)

when i use port 1091.

and I also see examples on port 5000

looking at the cfdestination code it runs an approuter so the port is for the app router

**Comment by stefania-santimbrean** [comment] 2021-12-17 09:50
> > @stefania-santimbrean still not working :( 401 unauthorized. default-env.json provided and everything set up as described ![image](https://user-images.githubusercontent.com/19520637/121897166-5e52d100-cd22-11eb-868b-9f20bcff118e.png)
> > It seems that when I make a request from the UI the authorization flow is not triggered by the middleware.
> 
> why port 1091?

@luizcarlospedrosogomes could you paste here your `xs-app.json`?

**Comment by luizcarlospedrosogomes** [comment] 2021-12-17 12:25
@stefania-santimbrean tanks for answer
```
{
  "welcomeFile": "/sprotargetmngt",
  "authenticationMethod": "route",
  
  "routes": [
    {
      "source": "^(.*)",
      "target": "$1",
      "authenticationType": "xsuaa",
      "service": "html5-apps-repo-rt"
    },
    {
      "source": "/target-mngt-api/(.*)",
      "target": "$1",
      "destination": "target-mngt-api",
      "scope": ["$XSAPPNAME.PartnerSales"],
      "authenticationType":"xsuaa",
      "csrfProtection": false
    }
  ]
}

```

**Comment by stefania-santimbrean** [comment] 2021-12-17 13:30
> @stefania-santimbrean tanks for answer
> 
> ```
> {
>   "welcomeFile": "/sprotargetmngt",
>   "authenticationMethod": "route",
>   
>   "routes": [
>     {
>       "source": "^(.*)",
>       "target": "$1",
>       "authenticationType": "xsuaa",
>       "service": "html5-apps-repo-rt"
>     },
>     {
>       "source": "/target-mngt-api/(.*)",
>       "target": "$1",
>       "destination": "target-mngt-api",
>       "scope": ["$XSAPPNAME.PartnerSales"],
>       "authenticationType":"xsuaa",
>       "csrfProtection": false
>     }
>   ]
> }
> ```

@luizcarlospedrosogomes no worries :D. The order of the routes is very important, the one for HTML5 repository must be the last one in the `xs-app.json`. This is my first observation. But it might still not work from other reasons. Try this first, to change the order of the 2 routes and let's see if it helps.

**Comment by luizcarlospedrosogomes** [comment] 2021-12-17 14:02
@stefania-santimbrean 

I gave up using port 1091, I'm using port 5000, but through cfdestination I have 401 status
I can only access the route when I start the app via /approuter -> npm start
I reordered the routes but without success.

![image](https://user-images.githubusercontent.com/9791364/146555767-c8339c10-8988-498a-b249-67dc2b0e7a46.png)


using port 1091 in ui5.yaml
![image](https://user-images.githubusercontent.com/9791364/146555839-62c36372-997f-48a7-b40a-a5806ad89eaa.png)

**Comment by luizcarlospedrosogomes** [comment] 2021-12-19 02:10
I noticed that when I remove the default-env.json the service goes up on port 1091.

**Comment by luizcarlospedrosogomes** [comment] 2021-12-20 12:37
after regenerating the app with yo easyui5 again and updating to the latest version of cfdestination, the app is connecting from my localhost to destination and respecting the roles.

thanks
